name: PalutenBoss
version: '${project.version}'
main: com.finley.palutenboss.PalutenBoss
description: A fan plugin for the youtuber "Paluten"
author: finleyjoel1yt
authors: [ finleyjoel1yt ]
load: POSTWORLD
website: https://www.spigotmc.org/resources/palutenboss.109389/
api-version: '1.20'

commands:
  palutenboss:
    description: A command for the palutenboss plugin.
    aliases:
      - paluten