name: PalutenBoss
version: 1.5
main: com.finley.palutenboss.PalutenBoss
description: A Fan-Plugin for the Youtuber "Paluten"
author: finleyjoel1yt
website: https://www.spigotmc.org/resources/palutenboss.109389/
api-version: '1.20'

commands:
  palutenboss:
    description: A command for the palutenboss plugin.
    aliases:
      - paluten